### ISSUE TITLE
/groups/attended/full error

### ISSUE THREAD

**Issue by maciek1651g** [Shady6/StudentOrganizer#19]
Gdy doda się harmonogram zajęć(schedule) pobranie danych z endpointu /groups/attended/full powoduje błąd. Gdy nie ma harmonogramu wszystko działa.

![image](https://user-images.githubusercontent.com/45820718/118372607-d5296c80-b5b2-11eb-9119-2c255b1c4be2.png)

**Comment by Shady6** [comment]
fixed
